/*===============================================================================
Copyright (c) 2015-2016 PTC Inc. All Rights Reserved.

Copyright (c) 2014 Qualcomm Connected Experiences, Inc. All Rights Reserved.

Vuforia is a trademark of PTC Inc., registered in the United States and other 
countries.

@file 
    PropResult.h

@brief
    Header file for PropResult class.
===============================================================================*/
#ifndef _VUFORIA_PROPRESULT_H_
#define _VUFORIA_PROPRESULT_H_

// Include files
#include <Vuforia/TrackableResult.h>
#include <Vuforia/Prop.h>

namespace Vuforia
{

/// Result for a Prop generated by the SmartTerrainTracker.
class VUFORIA_API PropResult : public TrackableResult
{
public:

    /// Returns the TrackableResult class' type
    static Type getClassType();

    /// Returns the corresponding Trackable that this result represents
    virtual const Prop& getTrackable() const = 0;
};

} // namespace Vuforia

#endif //_VUFORIA_PROPRESULT_H_
