/*===============================================================================
Copyright (c) 2014 Qualcomm Connected Experiences, Inc. All Rights Reserved.

Vuforia is a trademark of QUALCOMM Incorporated, registered in the United States 
and other countries. Trademarks of QUALCOMM Incorporated are used with permission.

@file 
    PropResult.h

@brief
    Header file for PropResult class.
===============================================================================*/
#ifndef _QCAR_PROPRESULT_H_
#define _QCAR_PROPRESULT_H_

// Include files
#include <QCAR/TrackableResult.h>
#include <QCAR/Prop.h>

namespace QCAR
{

/// Result for a Prop generated by the SmartTerrainTracker.
class QCAR_API PropResult : public TrackableResult
{
public:

    /// Returns the TrackableResult class' type
    static Type getClassType();

    /// Returns the corresponding Trackable that this result represents
    virtual const Prop& getTrackable() const = 0;
};

} // namespace QCAR

#endif //_QCAR_PROPRESULT_H_
